version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: electron_discord_dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - 3306:3306

  redis:
    image: redis:5
    ports:
      - '127.0.0.1:6379:6379'
